### ISSUE TITLE
UI freezes while creating dataset

### ISSUE THREAD

**Issue by dphilip** [KinkyDesign/JaqpotQuattroUI#87] opened 2016-07-25 10:27 UTC
While trying to create a dataset from 
https://apps.ideaconsult.net/enmtest/substanceowner/XLSX-e9b1d504-f54c-3968-aa61-0f0824169760
I select all descriptor option at http://test.jaqpot.org/descriptors except for Image descriptors and the UI freezes.

**Comment by hampos** [comment] 2016-07-26 06:48
@EvangelieAnagnostopoulou When this happens, UI app becomes completely unresponsive to other users as well, CPU usage on the running python script goes to 100%. I've limited the cores the script can use in order to avoid server crash, but still the app hangs completely.

@AValsamis There is a preparation task running behind this that never ends, keeps restarting because of error response from ambit. This happens by an unhandled exception in the MDB. The JMS framework will restart the task when it catches unhandled exceptions.

**Comment by dphilip** [comment] 2016-07-26 08:39
I asked Nina about the status of the new AMBIT server: they are doing tests now and she promised to have it online soon. Surely before the Athens workshop.

**Comment by hampos** [comment] 2016-09-10 17:35
Moving this to 4.0.3, as we haven't found the cause yet.

**Closed as completed** 2016-09-18 17:54 UTC
Labels: bug
